variable "account_tier" {}						
variable "account_replication_type" {}
variable "application" {}
variable "container_access_type" {}
variable "environment" {}
variable "location" {}
variable "resource_group_name" {}
variable "size" {}
variable "type" {}
